apiVersion: v1
kind: Service
metadata:
  name: ipmi-api-gateway
  labels:
    app: ipmi-api-gateway
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: ipmi-api-gateway